# Generated by Django 3.1 on 2020-11-08 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TypedUrls',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(verbose_name='Typed Urls')),
                ('dates', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
