# Generated by Django 3.1 on 2020-11-10 01:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='typedurls',
            old_name='url',
            new_name='url1',
        ),
    ]
