# Generated by Django 3.1 on 2020-11-10 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp_app', '0002_auto_20201110_0109'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='typedurls',
            name='url1',
        ),
        migrations.AddField(
            model_name='typedurls',
            name='entered_url',
            field=models.URLField(null=True, verbose_name='Entered Url'),
        ),
        migrations.AddField(
            model_name='typedurls',
            name='returned_url',
            field=models.URLField(null=True, verbose_name='Returned Url'),
        ),
    ]
