# Generated by Django 3.1 on 2020-11-10 01:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp_app', '0003_auto_20201110_0119'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='typedurls',
            options={'verbose_name_plural': 'Typed Urls'},
        ),
    ]
